### ISSUE TITLE
UI Menu Right Clicking

### ISSUE THREAD

**Issue by Johncrhamilton** [JR-Morgan/TeamProject-Game#65]
<h3>UI Menu Right Clicking</h3>
<ul>
<li>
After starting the game immediately right clicking will crash the game on line 196 in mouse input method.
</li>
<li>
Reasons as to why it crashes: It is possible that the Choose action menu needs to appear at least once before right clicking.
</li>
</ul>

**Comment by AccretionCD** [comment]
Fixed
